/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * HandsVeinWindow.java
 *
 * Created on Oct 24, 2012, 11:20:31 AM
 */
package handsveindetection;

import handsveindetection.buisness.FileMonitor;
import java.awt.BorderLayout;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.ComponentEvent;
import java.awt.event.ComponentListener;
import java.awt.event.WindowListener;
import java.io.FileInputStream;
import java.net.URL;
import java.util.Properties;
import javax.swing.ImageIcon;
import javax.swing.JInternalFrame;
import javax.swing.event.InternalFrameEvent;
import javax.swing.event.InternalFrameListener;
import javax.swing.JOptionPane;
/**
 *
 * @author Amar
 */
public class HandsVeinWindow extends javax.swing.JFrame {
    
    /** Creates new form HandsVeinWindow */
     Properties properties ;
    /** Creates new form HandsVeinWindow */
    public HandsVeinWindow() {
       initComponents1();
      try{
    	  FileMonitor fileMonitor= new FileMonitor();
    	  properties = fileMonitor.getResourceLocation();
    	      logframe.addInternalFrameListener(new InternalFrameListener() {

                @Override
                public void internalFrameOpened(InternalFrameEvent e) {
                //   loginButton.setEnabled(false);
                 //  registrationButton.setEnabled(false);
                }

                @Override
                public void internalFrameClosing(InternalFrameEvent e) {
                  
                }

                @Override
                public void internalFrameClosed(InternalFrameEvent e) {
                    loginButton.setEnabled(true);
                   registrationButton.setEnabled(true);
                }

                @Override
                public void internalFrameIconified(InternalFrameEvent e) {
                    
                }

                @Override
                public void internalFrameDeiconified(InternalFrameEvent e) {
                    
                }

                @Override
                public void internalFrameActivated(InternalFrameEvent e) {
                    
                }

                @Override
                public void internalFrameDeactivated(InternalFrameEvent e) {
                }
            });
              regframe.addInternalFrameListener(new InternalFrameListener() {

                @Override
                public void internalFrameOpened(InternalFrameEvent e) {
                //   registrationButton.setEnabled(false);
                 //  loginButton.setEnabled(false);
                }

                @Override
                public void internalFrameClosing(InternalFrameEvent e) {
                  
                }

                @Override
                public void internalFrameClosed(InternalFrameEvent e) {
                   registrationButton.setEnabled(true);
                    loginButton.setEnabled(true);
                }

                @Override
                public void internalFrameIconified(InternalFrameEvent e) {
                    
                }

                @Override
                public void internalFrameDeiconified(InternalFrameEvent e) {
                    
                }

                @Override
                public void internalFrameActivated(InternalFrameEvent e) {
                    
                }

                @Override
                public void internalFrameDeactivated(InternalFrameEvent e) {
                }
            });
//              
         }catch(Exception t){
            t.printStackTrace();
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        loginButton = new javax.swing.JButton();
        registrationButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        deskTopPane = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(619, 23));

        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        registrationButton.setText("Registration");
        registrationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrationButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setText("HandsVein Detection");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(loginButton)
                .addGap(269, 269, 269)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 352, Short.MAX_VALUE)
                .addComponent(registrationButton))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginButton)
                    .addComponent(jLabel1)
                    .addComponent(registrationButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 913, Short.MAX_VALUE)
            .addComponent(deskTopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 913, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deskTopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setBounds(0, 0, 929, 562);
    }// </editor-fold>//GEN-END:initComponents

    private void initComponents1() {
       jPanel1 = new javax.swing.JPanel();
        loginButton = new javax.swing.JButton();
        registrationButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        deskTopPane = new javax.swing.JDesktopPane(){
             ImageIcon backImage = new ImageIcon(getClass().getClassLoader().getResource("handsveindetection/resources/handsvein.png"));
             Image image = backImage.getImage();
             {setOpaque(false);}
             //Override
             public void paintComponent (Graphics g) {
               g.drawImage(image, 0, 0, this);
             //  System.out.println("Frme+++++++");
               super.paintComponent(g);
             }
             
        };

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(619, 23));

        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        registrationButton.setText("Registration");
        registrationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrationButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setText("HandsVein Detection");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(loginButton)
                .addGap(269, 269, 269)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 352, Short.MAX_VALUE)
                .addComponent(registrationButton))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginButton)
                    .addComponent(jLabel1)
                    .addComponent(registrationButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 913, Short.MAX_VALUE)
            .addComponent(deskTopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 913, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deskTopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setBounds(0, 0, 929, 562);
    }// </editor-fold>
    
    
private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
 logframe.add( hansVeinLogin, BorderLayout.CENTER ); 
 logframe.pack();
 logframe.setLocation(0,0);
 logframe.setVisible(true);
 deskTopPane.removeAll();
 deskTopPane.add(logframe); 
 registrationButton.setEnabled(false);
 FileMonitor.startFileMonitor(properties.getProperty("directory"), properties.getProperty("fileextension"),hansVeinLogin.getpasswordLabel(),null,null,null,null);

}//GEN-LAST:event_loginButtonActionPerformed

private void registrationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrationButtonActionPerformed
 regframe.add( handsVeinRegistration, BorderLayout.CENTER ); 
 regframe.pack();
 regframe.setLocation(0,0);
 regframe.setVisible(true);
 deskTopPane.removeAll();
 deskTopPane.add(regframe); 
 loginButton.setEnabled(false);
 FileMonitor.startFileMonitor(properties.getProperty("directory"), properties.getProperty("fileextension"),handsVeinRegistration.getpasswordLabel(),handsVeinRegistration.getGrayscaleImagelabel(),handsVeinRegistration.getHistogramImagelabel(),handsVeinRegistration.getiRImageLabel(),handsVeinRegistration.getSegementedImageLabel());
}//GEN-LAST:event_registrationButtonActionPerformed
   
    JInternalFrame logframe = new JInternalFrame("HandsVeinLogin Form", true, true, true, true );
    JInternalFrame regframe = new JInternalFrame( "HandsveinRegistration Form", true, true, true, true );
  public static   HandsVeinRegistration handsVeinRegistration = new HandsVeinRegistration();
  public static  HansVeinLogin hansVeinLogin   = new HansVeinLogin();
   // boolean isInternalFramIndeskTopPanel;
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane deskTopPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loginButton;
    private javax.swing.JButton registrationButton;
    // End of variables declaration//GEN-END:variables

   
    
}
